name: Generate Cypress Report

on:
  workflow_dispatch:
  
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
          
      - name: Run Cypress tests
        run: |          
          npm run cypress:run --config "baseUrl=https://development-sandbox-c341e.web.app"
        continue-on-error: true

      - name: Copy Cypress videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots
          
      - name: Generate HTML report
        run: npm run generate:html:report
      
      - name: Deploy HTML report to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
