name: Generate Cypress Report

on:
  workflow_dispatch:
  
jobs:
  cypress-test:
    name: Run on Chrome 83
    runs-on: ubuntu-18.04
    container: cypress/browsers:node16.13.2-chrome97-ff96
    steps:
      - uses: actions/checkout@v2

      - name: Install cypress and verify
        run: |
          npm ci
          $(npm bin)/cypress verify
          
      - name: Run Cypress tests
        run: |
          ng serve
          npm run test:chrome
        continue-on-error: true

      - name: Copy test execution videos and screenshots
        run: |
          mkdir public
          cp -r cypress/videos public/videos
          cp -r cypress/screenshots public/screenshots
          
      - name: Merge test reports and Generate HTML report
        run: npm run generate:html:report
      
      - name: Deploy report page to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          
