name: Generate Cypress Report

on:
  workflow_dispatch:
  
jobs:
  cypress-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install
        run: |
          npm ci
          
      - name: Run Cypress tests
        run: |          
          CYPRESS_baseUrl=https://development-sandbox-c341e.web.app npm run cypress:run
        continue-on-error: true
          
      - name: Generate HTML report
        run: npm run generate:html:report
      
      - name: Deploy HTML report to GitHub Page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./cypress-report
          
